# Generated by Django 5.1.2 on 2024-11-15 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planfeatures',
            options={'ordering': ['-is_active']},
        ),
        migrations.AlterField(
            model_name='planfeatures',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='common.plans'),
        ),
    ]
