# Generated by Django 5.1.2 on 2024-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_planfeatures_options_alter_planfeatures_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_name',
            field=models.CharField(max_length=50),
        ),
    ]
